import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { setTimeout as delay } from "node:timers/promises";
import { expect } from "@playwright/test";
import { database } from "../../server/db.mjs";
import { createApp } from "../../server/app.mjs";
import { hash, treeHash } from "../../server/security.mjs";
import { fixture, repo as platformRoot } from "../mcp/helpers.mjs";
import { executeProject } from "../../scripts/project-execution.mjs";
import { launchBrowser } from "../../scripts/browser.mjs";
import { runtimeIdentity } from "../../scripts/runtime-identity.mjs";
import { PREVIEW_VERSION } from "../../server/preview-version.mjs";
import { runAgentTurn } from "../../server/agent-runtime.mjs";
import { ingestAgentEvents } from "../../server/agent-event-store.mjs";
import { createAgentFileInspector } from "../../server/agent-file-changes.mjs";
import { agentModelServer } from "./fixtures/agent-model-server.mjs";

const url = process.env.FRAME_TEST_DATABASE_URL;
test("Agent workbench end-to-end: native CLI → persisted questions → browser answer → same-task command → real build/publication → notification and diff", { skip: !url, timeout: 180000 }, async (t) => {
  if (spawnSync("codex", ["--version"], { encoding: "utf8" }).status !== 0) { t.skip("A locally installed Codex CLI is required"); return; }
  const port = Number(process.env.FRAME_TEST_PORT || 55921), origin = `http://127.0.0.1:${port}`;
  const data = fs.mkdtempSync(path.join(os.tmpdir(), "frame-agent-browser-")), f = fixture({ browser: true });
  const report = path.join(platformRoot, ".cache/agent-chat/after"); fs.mkdirSync(report, { recursive: true });
  const db = await database(url, "fixture-password-at-least-14");
  await db.pool.query("TRUNCATE repos,connections,github_accounts,auth_flows RESTART IDENTITY CASCADE");
  const { app, actions, tasks, repos } = await createApp({ db, data, masterKey: "92".repeat(32), origin, scheduler: false });
  const call = (name, args = {}) => actions.call(name, args);
  const upstream = await agentModelServer({ provider: "codex", command: "printf 'checking current animation\\n'; sleep 2; printf '\\n// Human approved tighter pacing\\n' >> projects/test-film/scene.ts; printf 'Preserve music and subtitles.\\n' > projects/test-film/public/agent-note.txt; printf 'verified command output\\n'" });
  const controller = new AbortController(), errors = [], serverErrors = [], diagnostics = [];
  let browser, page, native, eventTimer;
  const previousPreview = process.env.FRAME_WORK_PREVIEW;
  process.env.FRAME_WORK_PREVIEW = "1";
  try {
    const connection = await call("connections_save", { name: "OpenAI · 隔离验收", tool: "codex", mode: "api", baseUrl: upstream.url + "/v1", apiKey: "fixture-agent-browser-key", model: "gpt-5.1-codex", models: [{ id: "gpt-5.1-codex", name: "Codex 原生协议验收", enabled: true }] });
    const repo = await call("repositories_add", { name: "Agent 创作验收" });
    fs.cpSync(f.file(""), path.join(data, "repos", repo.id, "projects/test-film"), { recursive: true });
    await actions.works.discover(repo.id);
    const work = (await call("works_page", { repo: repo.id })).items[0];
    const built = await executeProject(f.root, "test-film", "build"); assert.equal(built.status, "passed", JSON.stringify(built));
    const initialId = randomUUID(), relative = "projects/test-film/exports/preview";
    fs.cpSync(built.output, path.join(data, "runs", initialId, relative), { recursive: true });
    const initialCommit = await repos.checkpoint(repo.id, work.project, "验收基线");
    const fingerprint = treeHash(path.join(data, "works", work.id, "projects/test-film"));
    const runtime = await runtimeIdentity();
    await db.pool.query("INSERT INTO tasks(id,repo,project,kind,state,input,result,fingerprint,source_commit,finished) VALUES($1,$2,'test-film','build','succeeded','{}',$3,$4,$5,now())", [initialId, repo.id, { previewVersion: PREVIEW_VERSION, runtimeFingerprint: runtime.fingerprint, artifacts: [{ name: "index.html", path: relative + "/index.html" }] }, fingerprint, initialCommit]);
    const chat = await call("works_chat_create", { id: work.id, connection: connection.id, title: "开场节奏与声音优化" });
    await app.listen({ host: "127.0.0.1", port });
    browser = await launchBrowser();
    const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, permissions: ["clipboard-read", "clipboard-write"] });
    page = await context.newPage(); page.on("pageerror", (error) => errors.push(error.message));
    await page.goto(origin); await page.getByLabel("登录密码", { exact: true }).fill("fixture-password-at-least-14");
    await page.getByRole("button", { name: "进入工作台" }).click();
    await page.goto(origin + "/#/work/" + work.id);
    const textarea = page.getByRole("textbox", { name: "创作要求", exact: true });
    await textarea.fill("优化开场节奏，先确认我的偏好，保留音乐和字幕。");
    await page.getByRole("button", { name: "发送", exact: true }).click();
    await expect(textarea).toHaveValue("");
    const task = (await db.all("SELECT * FROM tasks WHERE chat=$1 ORDER BY created DESC", [chat.id]))[0]; assert(task);
    const run = path.join(data, "runs", task.id); fs.mkdirSync(run, { recursive: true });
    const home = path.join(data, "native-home"); fs.mkdirSync(path.join(home, "codex"), { recursive: true });
    const git = (...args) => execFileSync("git", args, { cwd: f.root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
    fs.writeFileSync(path.join(f.root, ".gitignore"), "node_modules/\n.cache/\nexports/\n");
    git("init", "-q"); git("add", "projects/test-film");
    git("-c", "user.name=Fixture", "-c", "user.email=fixture@local", "commit", "-qm", "Native task baseline");
    const log = path.join(run, "events.ndjson"), emit = (event) => fs.appendFileSync(log, JSON.stringify(event) + "\n");
    const inspect = createAgentFileInspector({ cwd: f.root, project: "test-film", baseline: git("rev-parse", "HEAD"), emit });
    const taskToken = "fixture-browser-task-" + randomUUID();
    await db.pool.query("INSERT INTO agent_tokens(hash,task) VALUES($1,$2)", [hash(taskToken), task.id]);
    await db.pool.query("UPDATE tasks SET state='running',started=now(),fingerprint=$2,source_commit=$3,base_commit=$3 WHERE id=$1", [task.id, fingerprint, initialCommit]);
    let draining = false;
    eventTimer = setInterval(async () => { if (draining) return; draining = true; try { await ingestAgentEvents(db, data, await tasks.get(task.id)); } catch (error) { serverErrors.push(error.message); } finally { draining = false; } }, 80);
    const env = { ...process.env, HOME: home, CODEX_HOME: path.join(home, "codex"), CODEX_API_KEY: "fixture-agent-browser-key", OPENAI_API_KEY: "fixture-agent-browser-key", FRAME_AGENT_URL: origin, FRAME_AGENT_TOKEN: taskToken, NO_PROXY: "127.0.0.1,localhost", no_proxy: "127.0.0.1,localhost" };
    for (const name of ["HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy"]) delete env[name];
    native = runAgentTurn({ provider: "codex", bin: "codex", task: { model: "gpt-5.1-codex", authMode: "api", baseUrl: upstream.url + "/v1" }, prompt: task.input.prompt, cwd: f.root, env, emit, signal: controller.signal, onToolComplete: inspect, onStderr: (value) => diagnostics.push(value) });
    native.catch(() => {});
    const q = page.locator(".agent-question.is-pending");
    await expect(q).toBeVisible({ timeout: 45000 });
    assert.equal(upstream.calls.length, 1, "The native CLI must be waiting for real browser input");
    assert.equal(fs.existsSync(f.file("public/agent-note.txt")), false);
    await page.screenshot({ path: path.join(report, "01-question-desktop.png") });
    await q.getByRole("radio", { name: /紧凑/ }).check();
    await q.getByRole("button", { name: "下一题", exact: true }).click();
    await q.getByRole("checkbox", { name: /音乐/ }).check();
    await page.reload();
    await expect(page.locator(".agent-question.is-pending")).toBeVisible();
    await expect(page.locator(".agent-question").getByRole("radio", { name: /紧凑/ })).toBeChecked();
    await page.locator(".agent-question").getByRole("button", { name: "下一题", exact: true }).click();
    await expect(page.locator(".agent-question").getByRole("checkbox", { name: /音乐/ })).toBeChecked();
    await page.locator(".agent-question").getByRole("checkbox", { name: /字幕/ }).check();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(report, "02-question-mobile.png") });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.setViewportSize({ width: 1440, height: 960 });
    await page.locator(".agent-question").getByRole("button", { name: "提交并继续", exact: true }).click();
    await expect(page.locator(".agent-question.is-resolved")).toContainText("紧凑");
    await page.locator(".agent-step-toggle").filter({ hasText: "执行命令" }).click();
    await expect(page.locator(".agent-terminal-output")).toContainText("checking current animation", { timeout: 30000 });
    await page.screenshot({ path: path.join(report, "03-running-command.png") });
    // Collapsing AI is NOT cancellation. Completion still becomes discoverable.
    await page.locator(".creation-actions").getByRole("button", { name: "关闭 AI 对话", exact: true }).click();
    const outcome = await native;
    await inspect(); await ingestAgentEvents(db, data, await tasks.get(task.id));
    assert(fs.readFileSync(f.file("scene.ts"), "utf8").includes("Human approved tighter pacing"));
    assert(upstream.calls.slice(1).some((input) => JSON.stringify(input).includes("紧凑")));
    assert.equal((await db.one("SELECT count(*)::int AS n FROM tasks WHERE chat=$1", [chat.id])).n, 1);
    const checked = await executeProject(f.root, "test-film", "typecheck"); assert.equal(checked.status, "passed", JSON.stringify(checked));
    const after = await executeProject(f.root, "test-film", "build"); assert.equal(after.status, "passed", JSON.stringify(after));
    fs.cpSync(f.file(""), path.join(run, "projects/test-film"), { recursive: true });
    const outputRelative = path.relative(f.root, after.output).replaceAll("\\", "/");
    const result = { upstream: outcome.upstream, previewVersion: PREVIEW_VERSION, runtimeFingerprint: runtime.fingerprint, previewArtifacts: [{ name: "index.html", path: outputRelative + "/index.html" }], validation: [{ name: "project-tests", state: "passed" }, { name: "preview-build", state: "passed" }] };
    fs.writeFileSync(path.join(run, "result.json"), JSON.stringify(result));
    await tasks.complete(await tasks.get(task.id), 0);
    const finished = await tasks.get(task.id); assert.equal(finished.state, "succeeded", JSON.stringify(finished.error));
    await expect(page.locator(".creation-actions .agent-notification-count")).toBeVisible();
    await page.locator(".creation-actions").getByRole("button", { name: "Agent 通知", exact: true }).click();
    const center = page.getByRole("dialog", { name: "Agent 通知", exact: true });
    await expect(center.getByText("创作已完成", { exact: true })).toBeVisible();
    await page.screenshot({ path: path.join(report, "04-notification-center.png") });
    await center.locator(".agent-notification-open").filter({ hasText: "创作已完成" }).click();
    await expect(page.locator(".creation-chat")).toBeVisible();
    await expect(page.locator("#agent-turn-" + task.id)).toBeVisible();
    await expect(page.getByRole("button", { name: "查看本轮预览与修改", exact: true })).toBeVisible();
    await page.screenshot({ path: path.join(report, "05-complete-desktop.png") });
    await page.getByRole("button", { name: "搜索对话内容", exact: true }).click();
    await page.getByRole("textbox", { name: "搜索已加载对话", exact: true }).fill("verified command output");
    await expect(page.locator(".agent-terminal-output")).toContainText("verified command output");
    await page.getByRole("button", { name: "关闭对话搜索", exact: true }).click();
    await page.locator(".agent-summary-toggle").click();
    await page.locator(".agent-change-summary").getByRole("button", { name: "查看文件差异 projects/test-film/scene.ts", exact: true }).click();
    const diff = page.getByRole("dialog", { name: "本轮文件变更", exact: true });
    await expect(diff).toContainText("Human approved tighter pacing");
    await page.screenshot({ path: path.join(report, "06-file-diff.png") });
    await diff.getByRole("button", { name: "关闭弹窗", exact: true }).click();
    await page.getByRole("button", { name: "查看本轮预览与修改", exact: true }).click();
    await expect(page.getByRole("button", { name: /^修改前 / })).toBeVisible();
    await page.getByRole("dialog").last().getByRole("button", { name: "关闭弹窗", exact: true }).click();
    for (const width of [1024, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 844 });
      await expect(textarea).toBeVisible();
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `No horizontal page overflow at ${width}`);
      if (width === 390) await page.screenshot({ path: path.join(report, "07-complete-mobile.png") });
    }
    assert.deepEqual(errors, []); assert.deepEqual(serverErrors, []);
    t.diagnostic("Real native Codex CLI, local model fixture, actual task-token API, PostgreSQL + WebSocket + browser questions, real command, validation/build, atomic publication and notification. No production credentials or production Docker tasks were used.");
  } catch (error) {
    fs.writeFileSync(path.join(report, "native-debug.json"), JSON.stringify({ diagnostics, calls: upstream.calls.map((c) => ({ model: c.model, input: c.input })), serverErrors }, null, 2));
    await page?.screenshot({ path: path.join(report, "failure.png"), fullPage: true }).catch(() => {});
    error.message += "\nBrowser errors: " + errors.join("; ") + "\nRuntime: " + diagnostics.join("").slice(-2000); throw error;
  } finally {
    clearInterval(eventTimer); controller.abort(); await native?.catch(() => {});
    await browser?.close(); await app.close(); await upstream.close();
    if (previousPreview === undefined) delete process.env.FRAME_WORK_PREVIEW; else process.env.FRAME_WORK_PREVIEW = previousPreview;
    f.close(); fs.rmSync(data, { recursive: true, force: true });
  }
});
