import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { stripTypeScriptTypes } from "node:module";

const source = new URL("./shared/bridge.ts", import.meta.url);
const output = new URL("./shared/bridge.mjs", import.meta.url);
const input = await readFile(source, "utf8");
const digest = createHash("sha256").update(input).digest("hex");
const expected = "// Generated by integrations/t3-code/build-shared.mjs; edit bridge.ts.\n" +
  "// Source SHA-256: " + digest + "\n" +
  stripTypeScriptTypes(input, { mode: "strip", sourceMap: false }).replace(/[ \t]+$/gm, "");
if (process.argv.includes("--check")) {
  if (await readFile(output, "utf8") !== expected) throw Error("T3 host protocol is stale; run node integrations/t3-code/build-shared.mjs");
} else if (await readFile(output, "utf8").catch(error => { if (error.code !== "ENOENT") throw error; return null; }) !== expected) await writeFile(output, expected);
