/** Shared capability catalog. "composition" is an engine-neutral document, not a drawing engine. */
export const adapters = Object.freeze([
  {
    id: "composition",
    name: "空白合成",
    category: "composition",
    template: true,
    seek: "absolute",
    alpha: true,
    offline: true,
  },
  {
    id: "canvas",
    name: "Canvas 2D",
    category: "2d",
    template: true,
    seek: "author",
    alpha: true,
    offline: true,
  },
  {
    id: "pixi",
    name: "PixiJS",
    category: "2d",
    template: true,
    seek: "author",
    alpha: true,
    offline: true,
  },
  {
    id: "three",
    name: "Three.js",
    category: "3d",
    template: true,
    seek: "author",
    alpha: true,
    offline: true,
  },
  {
    id: "babylon",
    name: "Babylon.js",
    category: "3d",
    template: true,
    seek: "author",
    alpha: true,
    offline: true,
  },
  {
    id: "lottie",
    name: "Lottie Canvas",
    category: "animation",
    template: false,
    seek: "absolute",
    alpha: true,
    offline: true,
  },
  {
    id: "video",
    name: "视频素材",
    category: "media",
    template: false,
    seek: "decoded",
    alpha: true,
    offline: true,
  },
  {
    id: "image",
    name: "图片素材",
    category: "media",
    template: false,
    seek: "absolute",
    alpha: true,
    offline: true,
  },
  {
    id: "sequence",
    name: "图像序列",
    category: "media",
    template: false,
    seek: "absolute",
    alpha: true,
    offline: true,
  },
]);
export const rendererIds = adapters.filter((a) => a.template).map((a) => a.id);
