import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { chromium } from "@playwright/test";

const [origin, output, data] = process.argv.slice(2);
if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(origin) || !output || !data) throw Error("Owned local application and evidence paths are required");
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
const wait = async (predicate, description, timeout = 120000) => {
  const until = Date.now() + timeout;
  while (Date.now() < until) { if (await predicate()) return; await sleep(250); }
  throw Error("Timed out: " + description);
};
const read = file => { try { return JSON.parse(fs.readFileSync(file, "utf8").replace(/^\uFEFF/, "")); } catch { return null; } };
const steps = [], errors = [];
const edge = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";
const browser = await chromium.launch({ executablePath: process.env.FRAME_BROWSER || (fs.existsSync(edge) ? edge : undefined), headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
const page = await context.newPage();
page.on("pageerror", error => errors.push(error.message));
const capture = name => page.screenshot({ path: path.join(output, name + ".png") });
const pass = message => { steps.push(message); console.log("PASS: " + message); };
const get = async route => { const response = await context.request.get(origin + route); assert.ok(response.ok(), await response.text()); return response.json(); };
const post = async (route, value) => context.request.post(origin + route, { headers: { Origin: origin }, data: value });
const action = async (name, args) => { const response = await post("/api/action", { name, args }); assert.ok(response.ok(), name + ": " + await response.text()); return response.json(); };
let command = 0;
const native = async action => {
  const id = String(++command);
  fs.writeFileSync(path.join(output, "native-command.json"), JSON.stringify({ id, action }));
  await wait(() => read(path.join(output, "native-result.json"))?.id === id, "native " + action, 120000);
  return read(path.join(output, "native-result.json"));
};
const idle = () => wait(async () => !(await get("/api/desktop/status")).active, "task queue idle");
const taskDone = id => wait(async () => {
  const value = (await action("task_get", { id })).task;
  assert.notEqual(value.state, "failed", JSON.stringify(value));
  return value.state === "succeeded";
}, "native task " + id);
try {
  await page.goto(origin);
  await page.locator(".workbench").waitFor();
  assert.equal(await page.locator('input[type="password"]').count(), 0);
  await page.getByText("从一个想法开始", { exact: true }).waitFor();
  await capture("browser-welcome");
  await page.locator(".library-heading").getByRole("button", { name: "新建作品", exact: true }).click();
  await page.locator('input[name="title"]').fill("Windows 浏览器验收作品");
  await wait(async () => (await get("/api/desktop/status")).unsaved > 0, "browser unsaved activity");
  assert.equal((await native("exit")).disposed, false);
  pass("Windows exit defers while the browser has unsaved input");
  await page.getByRole("button", { name: "创建并开始创作", exact: true }).click();
  await page.waitForURL("**/#/work/*");
  await page.locator(".workspace").waitFor();
  const work = new URL(page.url()).hash.split("/")[2];
  await idle();
  await page.locator('iframe[title="作品播放器"]').waitFor({ timeout: 120000 });
  await capture("browser-work");
  assert.equal(context.pages().length, 1);
  pass("password-free browser workbench creates a first work without repository setup");
  await page.goto(origin + "/#/settings/ai");
  await page.getByText("本机 AI 助手", { exact: true }).waitFor();
  await page.locator(".desktop-ai-card").first().waitFor();
  assert.equal(await page.locator(".desktop-ai-card").count(), 2);
  assert.equal(await page.getByText("API Key", { exact: true }).count(), 0);
  await capture("browser-ai");
  pass("browser AI settings show installed CLI and login availability");
  await page.goto(origin + "/#/settings/desktop");
  await page.getByRole("button", { name: "打开应用更新", exact: true }).click();
  await capture("browser-center-link");
  assert.equal(await page.locator("progress, .desktop-toggle").count(), 0);
  pass("browser settings open the native Windows center without embedding it");
  const forbidden = await post("/api/desktop/prepare-exit", {});
  assert.equal(forbidden.status(), 403);
  await idle();
  const frame = await action("works_task", { id: work, kind: "frame", input: { time: 0, width: 640 } });
  assert.ok((await get("/api/desktop/status")).active > 0);
  assert.equal((await native("restart")).disposed, false);
  await taskDone(frame.id);
  pass("native frame render completes while a busy restart is deferred");
  const render = await action("works_task", { id: work, kind: "render", input: { start: 0, end: 1, width: 640, fps: 12 } });
  await taskDone(render.id);
  assert.ok((await action("works_exports", { id: work })).length > 0);
  pass("Windows native MP4 export completes");
  const build = await action("works_task", { id: work, kind: "build", input: {} });
  await taskDone(build.id);
  await page.goto(origin + "/#/work/" + work);
  await page.locator('iframe[title="作品播放器"]').waitFor({ timeout: 120000 });
  await page.frameLocator('iframe[title="作品播放器"]').locator("canvas").first().waitFor({ timeout: 60000 });
  await capture("browser-preview");
  pass("built animation preview renders in the browser");
  const repo = (await action("repositories_page", {})).items[0];
  const reactWork = await action("works_create", { repo: repo.id, title: "Windows Remotion 验收", renderer: "remotion", duration: 2, width: 640, height: 360, fps: 24 });
  const reactFrame = await action("works_task", { id: reactWork.id, kind: "frame", input: { time: 0.5, width: 640 } });
  await taskDone(reactFrame.id);
  const reactRender = await action("works_task", { id: reactWork.id, kind: "render", input: { start: 0, end: 1, width: 640, fps: 24 } });
  await taskDone(reactRender.id);
  assert.ok((await action("works_exports", { id: reactWork.id })).length > 0);
  pass("merged Remotion renderer completes a Windows native frame and MP4 export");
  await page.goto(origin + "/");
  await wait(async () => !(await get("/api/desktop/status")).unsaved, "saved browser state");
  const before = read(path.join(data, "desktop-test-ready.json"));
  assert.equal((await native("restart")).disposed, false);
  const after = read(path.join(data, "desktop-test-ready.json"));
  assert.notEqual(before.server, after.server);
  assert.equal(before.origin, after.origin);
  await page.reload();
  await page.locator(".workbench").waitFor();
  assert.equal((await action("works_page", {})).total, 2);
  pass("restart preserves the browser address and SQLite works");
  await wait(async () => (await get("/api/desktop/status")).speech.state === "ready", "speech service readiness");
  await native("fault-service");
  await native("restart");
  await wait(async () => (await get("/api/desktop/status")).speech.state === "ready", "speech crash recovery");
  await page.reload(); await page.locator(".workbench").waitFor();
  pass("owned server failure recovers with speech mount cleanup and preserved browser works");
  assert.equal((await native("hide")).visible, false);
  assert.ok((await get("/api/me")).localMode);
  await native("show");
  await native("browser");
  assert.equal(read(path.join(data, "desktop-test-browser.json")).url, origin + "/");
  pass("closing the Windows center keeps the browser service running; browser action uses its URL");
  assert.deepEqual(errors, []);
  fs.writeFileSync(path.join(output, "browser-result.json"), JSON.stringify({ state: "done", steps }, null, 2));
} catch (error) {
  await capture("browser-failed").catch(() => {});
  fs.writeFileSync(path.join(output, "browser-result.json"), JSON.stringify({ state: "failed", steps, error: error.stack, errors }, null, 2));
  throw error;
} finally {
  await context.close(); await browser.close();
  fs.writeFileSync(path.join(output, "browser-done.json"), "{}");
}
