// Generated by integrations/t3-code/build-shared.mjs; edit bridge.ts.
// Source SHA-256: 42871d8f216ecd436a36042877996308df65dd9aa92c54d11431da110baa5542
/** FRAME's host protocol is independent of the native UI's dependencies. */
























export const frameOperations = ["context.read", "context.subscribe", "context.attach", "freeze.submit",
  "message.accepted", "preview.open", "results.open", "dock.close"]         ;




const fail = (message        )        => { throw new TypeError(message); };
const record = (value         )                          =>
  value !== null && typeof value === "object" && !Array.isArray(value)
    ? value                            : fail("Expected an object");
const text = (max = 256, min = 1)        => value => {
  if (typeof value !== "string" || value.length < min || value.length > max) fail("Invalid string");
};
const matching = (pattern        )        => value => {
  text()(value); if (!pattern.test(value          )) fail("Invalid identifier");
};
const uuid = matching(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);
const sha = matching(/^[a-f0-9]{64}$/);
const choice = (values                    )        => value => {
  if (!values.includes(value)) fail("Invalid protocol value");
};
const array = (check       , max        )        => value => {
  if (!Array.isArray(value) || value.length > max) fail("Invalid array");
  (value             ).forEach(check);
};
const finiteTime        = value => {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || value > 3600) fail("Invalid time");
};
const url        = value => { text(8192)(value); new URL(value          ); };
const object = (required                       , optional                        = {})        => value => {
  const item = record(value);
  for (const key of Object.keys(item)) if (!(key in required) && !(key in optional)) fail("Unexpected field: " + key);
  for (const [key, check] of Object.entries(required)) check(item[key]);
  for (const [key, check] of Object.entries(optional)) if (item[key] !== undefined) check(item[key]);
};
const schema =    (check       ) => ({
  parse(value         )    { check(value); return value     ; },
  safeParse(value         )                                                                  {
    try { check(value); return { success: true, data: value      }; }
    catch (error) { return { success: false, error }; }
  },
});
const review        = value => {
  object({}, { time: finiteTime, start: finiteTime, end: finiteTime,
    shotId: matching(/^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,95}$/), assets: array(uuid, 20),
    previewTask: uuid, sourceCommit: matching(/^[a-f0-9]{40}$/), liveSessionId: uuid,
    sourceRevision: sha, compiledRevision: sha })(value);
  const item = record(value);
  if ((item.start === undefined) !== (item.end === undefined) ||
      (item.start !== undefined && (item.end          ) <= (item.start          ))) fail("The range end must follow its start");
  if ((item.liveSessionId === undefined) !== (item.sourceRevision === undefined)) fail("A live reference needs its source revision");
  if (item.liveSessionId !== undefined && (item.previewTask !== undefined || item.sourceCommit !== undefined)) fail("A live reference cannot mix snapshot identifiers");
  if (item.compiledRevision !== undefined && item.liveSessionId === undefined) fail("A compiled revision needs its live session");
};
export const FrameReviewContextSchema = schema                    (review);
export const FrameBootstrapSchema = schema                (object({ version: choice([1]), workId: uuid,
  projectId: text(), environmentId: text(), cwd: text(4096), label: text(160), userScope: text(128),
  parentOrigin: url, nonce: matching(/^[A-Za-z0-9_-]{24,128}$/),
  basePath: choice(["/ai/"]), embedPath: text(4096) }));
export const FrameFreezeInputSchema = schema                  (object({ threadId: text(), messageId: uuid,
  text: text(2_000_000, 0), nativeProjectId: text(), cwd: text(4096),
  selection: object({ instanceId: text(), model: text() }) }, { reference: review, screenshots: array(() => {}, 20) }));
export const FrameFreezeResponseSchema = schema                     (object({ version: choice([1]), workId: uuid,
  threadId: text(), messageId: uuid, intentHash: sha, context: review, reviewReference: value => { record(value); } },
  { attachment: object({ type: choice(["text"]), mimeType: choice(["text/plain"]), text: text(2_000_000, 0) },
    { title: value => { if (value !== null) text(512, 0)(value); } }) }));
export const FrameOperationSchema = schema                (choice(frameOperations));
export const FrameConnectSchema = schema                                                                         (
  object({ type: choice(["frame-ai-connect"]), version: choice([1]), workId: uuid,
    nonce: matching(/^[A-Za-z0-9_-]{24,128}$/) }));
export const FramePortRequestSchema = schema                  (object({ type: choice(["request"]), id: uuid,
  op: choice(frameOperations), payload: () => {} }));
export const FramePortMessageSchema = schema                         (value => {
  const item = record(value);
  if (item.type === "connected") object({ type: choice(["connected"]), version: choice([1]), workId: uuid, nonce: text(128) })(value);
  else if (item.type === "response") object({ type: choice(["response"]), id: uuid, ok: choice([true, false]) },
    item.ok === true ? { payload: () => {} } : { error: object({ code: text(), message: text(4096, 0) }) })(value);
  else object({ type: choice(["event"]), event: choice(["context.attach", "disposed"]), payload: () => {} })(value);
});
export const FrameContextAttachmentSchema = schema                        (object({ id: text(), title: text(512),
  url, text: text(2_000_000, 0), resourceType: text() }, { identifier: text(), subtitle: text(4096, 0) }));
export const FrameContextAttachmentEventSchema = schema                                                    (
  object({ threadId: text(), item: value => { FrameContextAttachmentSchema.parse(value); } }));

export function frameReviewUrl(workId        , context                    , baseUrl        )         {
  uuid(workId); const reference = { version: 1, workId, context: FrameReviewContextSchema.parse(context) };
  const value = new URL(baseUrl);
  if (!["http:", "https:"].includes(value.protocol)) fail("A FRAME review link must use HTTP or HTTPS");
  value.search = "";
  value.searchParams.set("frameReference", JSON.stringify(reference)); value.hash = "/work/" + workId;
  return value.href;
}

/** Read a persisted native message link without consulting the current player selection. */
export function readFrameReviewUrl(rawUrl              , workId        )                            {
  const encoded = new URL(rawUrl).searchParams.get("frameReference");
  if (encoded === null) return null;
  if (encoded.length > 4096) fail("Oversized FRAME reference");
  const value = JSON.parse(encoded);
  object({ version: choice([1]), workId: uuid, context: review })(value);
  if (value.context.time === undefined && value.context.start === undefined) fail("Missing recorded position");
  return value.workId === workId ? value.context : null;
}

/** All attached references must describe one source; the latest timecode is the primary image. */
export function frameAttachedReview(items                                   , workId        )                                 {
  let reference                                ;
  let provenance                    ;
  const assets = new Set        ();
  for (const item of items) {
    const context = readFrameReviewUrl(item.url, workId);
    if (!context) continue;
    const identity = JSON.stringify([context.liveSessionId, context.sourceRevision, context.compiledRevision, context.previewTask, context.sourceCommit]);
    if (provenance !== undefined && identity !== provenance) fail("Attached FRAME references use different preview versions. Remove the older reference before sending.");
    provenance = identity; reference = context;
    for (const asset of context.assets ?? []) assets.add(asset);
  }
  if (assets.size > 20) fail("A FRAME message can reference at most 20 materials");
  return reference ? { ...reference, ...(assets.size ? { assets: [...assets] } : {}) } : undefined;
}
