import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { stripTypeScriptTypes } from 'node:module';

const source = new URL('./frame-plugin/shared/bridge.ts', import.meta.url);
const output = new URL('./frame-plugin/shared/bridge.mjs', import.meta.url);
const input = await readFile(source, 'utf8');
const sha = createHash('sha256').update(input).digest('hex');
const compiled = stripTypeScriptTypes(input, { mode: 'strip', sourceMap: false })
  .replace(/[ \t]+$/gm, '');
const expected = '// Generated by integrations/paseo/build-shared.mjs; edit bridge.ts.\n' +
  '// Source SHA-256: ' + sha + '\n' + compiled;
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== expected) {
    throw new Error('Paseo bridge.mjs is stale. Run node integrations/paseo/build-shared.mjs.');
  }
} else {
  await writeFile(output, expected);
}
console.log('Paseo bridge generated schema verified: ' + sha);
